import CtaBox from "../components/CtaBox1";
import Header from "../components/Header";
import TitleAreaCenter from "../components/TitleAreaCenter";
import IbAnimation from "../components/animations/IbAnimation";
import { Link } from "react-router-dom";
import { handleRedirect } from "../lib/redirectLocationHandler";

const stepsData = [
  {
    id: 1,
    icon: "/images/icons/register.png",
    title: "1. Register",
    description:
      "Fill out a simple application form, and we'll review it on the same day.",
  },
  {
    id: 2,
    icon: "/images/icons/refer.png",
    title: "2. Refer",
    description:
      "After signing up, you'll receive a tracking link that gives you access to our marketing and operational tools.",
  },
  {
    id: 3,
    icon: "/images/icons/earn-reward.png",
    title: "3. Earn Rewards",
    description:
      "Send us your leads, and you'll start earning as soon as they begin trading.",
  },
];

const referralSteps = [
  {
    title: "Refer Traders",
    desc: "Simply introduce traders to Fastone Markets. Once they open an account and start trading, your earnings begin.",
  },
  {
    title: "Earn as They Trade",
    desc: "You earn up to 75% of the revenue generated by each active trader you refer. This revenue comes from the trading fees, spreads, and commissions that Fastone Markets collects from their trading activities.",
  },
  {
    title: "Continuous Income",
    desc: "As long as your referred traders remain active, your income continues. The more they trade, the more you earn.",
  },
];

const partnerFeatures = [
  {
    title: "Same-Day Deposits and Withdrawals",
    desc: "Offer your clients the convenience of same-day deposits and withdrawals, enhancing their trading experience and trust in your partnership.",
  },
  {
    title: "Comprehensive Support",
    desc: "Partner with a leading CFD provider that offers full marketing, technical, and client support, empowering you to focus on growing your business.",
  },
  {
    title: "Daily Market Technical and Fundamental Support",
    desc: "Equip your clients with daily market analysis, technical insights, and fundamental updates to help them make informed trading decisions.",
  },
  {
    title: "Advanced Trading Environment",
    desc: "Offer your clients top-tier trading tools, competitive spreads, and high leverage up to 1:500, making FastOne Markets a preferred choice for serious traders.",
  },
  {
    title: "Diverse Asset Offering",
    desc: "Attract more clients by offering a wide range of trading instruments, including forex, precious metals, and CFDs, all on a single platform.",
  },
  {
    title: "Reputation and Reliability",
    desc: "Benefit from our strong market presence, robust security measures, and commitment to transparency, making FastOne Markets a trusted partner in the financial industry.",
  },
];

function IntroducingBroker() {
  const breadcrumbPaths = [
    { name: "Home", href: "/" },
    { name: "Partners", href: "" },
    { name: "Introducing Broker" },
  ];
  const handleLinkClick = (event, isLogin) => {
    event.preventDefault();
    handleRedirect(isLogin);
  };
  return (
    <div className="bg-[#030B20]">
      <Header />
      <TitleAreaCenter
        title="Introducing Broker"
        description="Earn 75% of our revenue. At Fastone Markets, we believe in rewarding our partners generously. Our Introducing Broker Program is designed to offer you the opportunity to earn a significant portion of the revenue generated by the traders you refer. The more they trade, the more you earn!"
        breadcrumbPaths={breadcrumbPaths}
      />

      <section className="wc-fmarket wc-fm-2">
        <div className="container">
          <div className="flex justify-center items-start    partner-img-1">
            {/* <IbAnimation /> */}
            <div className=" lg:max-w-4xl">
              {" "}
              <img src="/images/BROKER.png" alt="" />
            </div>
          </div>
          {/* <div className="row partner-img-1">
            <img src="/images/BROKER.png" alt="" />
          </div> */}
          {/* <div className="flex flex-col items-center md:items-stretch md:flex-row md:justify-between gap-4 px-4 md:px-0">
            <div className="md:w-1/3 w-full wcfm-col">
              <p>
                Partner with FastOne Markets - where your referrals lead to real
                rewards. Enjoy high commissions and support at every step.
              </p>
            </div>
            <div className="md:w-1/3 w-full wcfm-col">
              <p>
                Maximize your earnings while offering top-tier trading
                conditions.
              </p>
            </div>
            <div className="md:w-1/3 w-full wcfm-col">
              <p>
                Join FastOne Markets' IB program and enjoy best earning programs
                and per lot commissions.
              </p>
            </div>
          </div> */}
        </div>
      </section>

      {/* Gradient border wrapper */}
      <section className="container mx-auto">
        <div className="p-[2px] bg-gradient-to-r from-[#4575FF] to-[#92AEFF] rounded-xl my-8 mx-4 md:mx-20 lg:mx-20">
          {/* <section className="p-[2px] bg-gradient-to-r from-[#4575FF] to-[#92AEFF] rounded-xl my-8 mx-4 md:mx-20 lg:mx-20"> */}
          {/* Inner content with solid background */}
          <div className="bg-[#030B20] text-white rounded-xl p-6 lg:p-10">
            <div className="lg:container">
              <div className="row inf-cta-title flex flex-col md:flex-row gap-4">
                {/* Heading Block */}
                <div className="w-full md:w-1/2 flex items-center font-bold">
                  <h2 className="wcu-title bg-gradient-to-r from-[#4575FF] to-[#92AEFF] bg-clip-text text-transparent text-3xl">
                    Interested in IB Partnership opportunities??
                  </h2>
                </div>

                {/* Vertical Line + Paragraph */}
                <div className="w-full md:w-1/2 flex items-center gap-4">
                  {/* Vertical Line */}
                  <div
                    className="w-full sm:w-0.5 sm:h-auto h-0.5 sm:self-stretch bg-gradient-to-r sm:bg-gradient-to-b hidden sm:block"
                    style={{
                      backgroundImage: `linear-gradient(to bottom, #000 0%, #92aeff 24%, #4575ff 77%, #000 98%)`,
                    }}
                  />

                  {/* Vertical line for mobile only */}
                  <div className="w-0.5 h-25 bg-gradient-to-b from-black/20 via-[#92aeff] to-[#4575ff] block sm:hidden" />

                  {/* Paragraph */}
                  <div className="flex-1">
                    <p>
                      Join our IB Program today and elevate your business with
                      our unparalleled support and resources. Experience the
                      benefits of partnering with a leading CFD provider and
                      watch your success grow!
                    </p>
                  </div>
                </div>
              </div>

              {/* Steps */}
              <div className="flex flex-col md:flex-row items-start md:justify-between gap-6 md:mt-8 text-left md:text-center md:py-8">
                {stepsData.map((step) => (
                  <div
                    key={step.id}
                    className="w-full md:w-1/3 flex flex-col items-center justify-start gap-4 min-h-[300px]"
                  >
                    <img src={step.icon} alt="" className="inf-icon mb-4" />
                    <h3 className="text-2xl mb-4">{step.title}</h3>
                    <p className="mb-0">{step.description}</p>
                  </div>
                ))}
              </div>

              {/* CTA Button */}
              <div className="inf-cta-btn text-left !text-[#1368A6]">
                <Link
                  to="#"
                  onClick={(e) => handleLinkClick(e, false)}
                  className="btn-one rounded-btn inf-account"
                >
                  Create your Partner Account
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto">
        <div className="p-[2px] bg-gradient-to-r from-[#4575FF] to-[#92AEFF] rounded-xl my-8 mx-4 md:mx-20">
          <div className="bg-[#030B20] rounded-xl text-white">
            <div className="flex flex-col md:flex-row justify-between text-left ">
              {referralSteps.map((item, index) => (
                <div
                  key={index}
                  className={`w-full flex flex-col gap-3 py-6 xl:py-8 px-6 xl:px-14 border-t md:border-t-0 md:border-l-0 md:border-r ${
                    index === 0
                      ? "md:border-r"
                      : index === 1
                      ? "md:border-r"
                      : "md:border-r-0"
                  } border-[#4575FF] `}
                >
                  <h3 className="text-2xl font-semibold">{item.title}</h3>
                  <p>{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto">
        <div className="p-[2px] bg-gradient-to-r from-[#4575FF] to-[#92AEFF] rounded-xl my-8 mx-4 md:mx-20">
          <div className="wc-fmarket bg-[#030B20] text-white rounded-xl py-10 px-6 md:px-12">
            <div className="container">
              <h2 className="text-3xl font-semibold mb-8 text-left md:text-center">
                Why Choose Fastone Markets?
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 3xl:mx-10">
                {[
                  {
                    title: "High Payouts",
                    desc: "With a revenue share of up to 75%, we offer one of the most competitive IB programs in the industry.",
                  },
                  {
                    title: "Advanced Trading Platform",
                    desc: "Your clients will have access to cutting-edge trading technology, ensuring they have the best tools to succeed.",
                  },
                  {
                    title: "Comprehensive Support",
                    desc: "We provide full support to help you grow your business, including marketing materials, dedicated account managers, and regular performance reports.",
                  },
                  {
                    title: "Transparent Reporting",
                    desc: "Stay updated with detailed reports that track your referrals and earnings in real-time.",
                  },
                ].map((item, idx) => (
                  <div
                    key={idx}
                    className="flex flex-col sm:flex-row items-start sm:items-center gap-4"
                  >
                    {/* Line (Vertical on tablet and above, Horizontal on mobile) */}
                    <div
                      className="w-full sm:w-0.5 sm:h-auto h-0.5 sm:self-stretch bg-gradient-to-r sm:bg-gradient-to-b"
                      style={{
                        backgroundImage:
                          "linear-gradient(to bottom, #0F2567 0%, #92AEFF 24%, #4575FF 77%, #0F2567 100%)",
                      }}
                    />
                    {/* Content */}
                    <div className="flex-1 text-left">
                      <h3 className="text-2xl font-semibold mb-2">
                        {item.title}
                      </h3>
                      <p>{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto">
        <div className="ib-cta mx-2 md:mx-15">
          <div className="container">
            <div className="row justify-content-center text-center">
              <div className="col-md-12">
                <h2 className="display-4">
                  Join Our Network of Successful IBs
                </h2>
                <p className="lead px-lg-12 m-5 text-[#B2B2B2] md:mx-20">
                  Become a part of Fastone Markets' growing community of
                  Introducing Brokers and start earning today. Whether you’re an
                  individual or a company, our program is designed to help you
                  succeed.
                </p>
                <div className="d-flex justify-content-center pt-8">
                  <Link
                    to="#"
                    onClick={(e) => handleLinkClick(e, false)}
                    className="btn-one rounded-btn white-btn"
                  >
                    Partner with us
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto">
        <div className="p-[2px] bg-gradient-to-r from-[#4575FF] to-[#92AEFF] rounded-xl my-8 mx-4 md:mx-20">
          <div className="bg-[#030B20] text-white rounded-xl py-10 px-0">
            <div className="container mx-auto">
              {/* Heading Section */}
              <div className="mb-10 px-6 md:px-12 text-center">
                <h2 className="text-3xl font-semibold mb-4">
                  Why partner with Fastone Markets?
                </h2>
                <p className="text-lg text-[#B2B2B2]">
                  Lucrative Commission Structure: Ensuring consistent and
                  substantial revenue, regardless of market conditions.
                </p>
              </div>

              {/* Grid Section */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 3xl:mx-10">
                {partnerFeatures.map((item, idx) => (
                  <div
                    key={idx}
                    className="flex flex-col sm:flex-row items-start sm:items-center gap-4 sm:gap-0"
                  >
                    {/* Line - Flush Left */}
                    <div
                      className="w-full sm:w-0.5 sm:h-auto h-0.5 sm:self-stretch bg-gradient-to-r sm:bg-gradient-to-b"
                      style={{
                        backgroundImage:
                          "linear-gradient(to bottom, #0F2567 0%, #92AEFF 24%, #4575FF 77%, #0F2567 100%)",
                      }}
                    />
                    {/* Content - With Padding */}
                    <div className="flex-1 text-left px-6 md:px-4">
                      <h3 className="text-2xl font-semibold mb-2">
                        {item.title}
                      </h3>
                      <p className="text-[#B2B2B2]">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="container mx-auto">
        <div className="my-8 mx-4 md:mx-20">
          <div className="bg-[#030B20] text-white rounded-xl py-10 px-0">
            <CtaBox
              heading="Still confused which partnership to choose ?"
              description="Talk to our partnership expert now!"
              buttonText="Live Chat"
              buttonImage="/images/icons/chat.png"
              sectionColor="#1368A6"
              opacity="20"
            />{" "}
          </div>
        </div>
      </section>
    </div>
  );
}

export default IntroducingBroker;
